routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\PriceController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\ButtonController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\AuthenticationController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [UserController::class, 'Dashboard'])->name('dashboard');

Route::get('login', [AuthenticationController::class, 'form'])->name('login')->middleware('guest');
Route::post('authenticate', [AuthenticationController::class, 'authenticate']);
Route::get('logout', [AuthenticationController::class, 'logout'])->middleware('auth')->name('logout');


Route::middleware('auth')->group(function () {
    Route::get('/admin', [AdminController::class, 'Index'])->name('admin');
    // admin-feature
    Route::group(['prefix' => 'admin', 'as' => 'feature.'], function(){
        Route::get('/feature', [FeatureController::class, 'index'])->name('index');
        Route::get('/feature/create', [FeatureController::class, 'create'])->name('create');
        Route::post('/feature/store', [FeatureController::class, 'store'])->name('store');
        Route::get('/feature/edit/{feature}', [FeatureController::class, 'edit'])->name('edit');
        Route::post('/feature/update/{feature}', [FeatureController::class, 'update'])->name('update');
        Route::get('/feature/delete/{feature}', [FeatureController::class, 'destroy'])->name('delete');
    });    
    // admin-image
    Route::group(['prefix' => 'admin', 'as' => 'image.'], function(){
        Route::get('/image', [ImageController::class, 'index'])->name('index');
        Route::get('/image/create', [ImageController::class, 'create'])->name('create');
        Route::post('/image/store', [ImageController::class, 'store'])->name('store');
        Route::get('/image/edit/{image}', [ImageController::class, 'edit'])->name('edit');
        Route::post('/image/update/{image}', [ImageController::class, 'update'])->name('update');
        Route::get('/image/delete/{image}', [ImageController::class, 'destroy'])->name('delete');
    }); 
    // admin-price
    Route::group(['prefix' => 'admin', 'as' => 'price.'], function(){
        Route::get('/price', [PriceController::class, 'index'])->name('index');
        Route::get('/price/create', [PriceController::class, 'create'])->name('create');
        Route::post('/price/store', [PriceController::class, 'store'])->name('store');
        Route::get('/price/edit/{price}', [PriceController::class, 'edit'])->name('edit');
        Route::post('/price/update/{price}', [PriceController::class, 'update'])->name('update');
        Route::get('/price/delete/{price}', [PriceController::class, 'destroy'])->name('delete');
    });
    // admin-contact
    Route::group(['prefix' => 'admin', 'as' => 'contact.'], function(){
        Route::get('/contact', [ContactController::class, 'index'])->name('index');
        Route::get('/contact/create', [ContactController::class, 'create'])->name('create');
        Route::post('/contact/store', [ContactController::class, 'store'])->name('store');
        Route::get('/contact/edit/{contact}', [ContactController::class, 'edit'])->name('edit');
        Route::post('/contact/update/{contact}', [ContactController::class, 'update'])->name('update');
        Route::get('/contact/delete/{contact}', [ContactController::class, 'destroy'])->name('delete');
    });
    // admin-banner
    Route::group(['prefix' => 'admin', 'as' => 'banner.'], function(){
        Route::get('/banner', [BannerController::class, 'index'])->name('index');
        Route::get('/banner/create', [BannerController::class, 'create'])->name('create');
        Route::post('/banner/store', [BannerController::class, 'store'])->name('store');
        Route::get('/banner/edit/{banner}', [BannerController::class, 'edit'])->name('edit');
        Route::post('/banner/update/{banner}', [BannerController::class, 'update'])->name('update');
        Route::get('/banner/delete/{banner}', [BannerController::class, 'destroy'])->name('delete');
    });
    // admin-button
    Route::group(['prefix' => 'admin', 'as' => 'button.'], function(){
        Route::get('/button', [ButtonController::class, 'index'])->name('index');
        Route::get('/button/create', [ButtonController::class, 'create'])->name('create');
        Route::post('/button/store', [ButtonController::class, 'store'])->name('store');
        Route::get('/button/edit/{button}', [ButtonController::class, 'edit'])->name('edit');
        Route::post('/button/update/{button}', [ButtonController::class, 'update'])->name('update');
        Route::get('/button/delete/{button}', [ButtonController::class, 'destroy'])->name('delete');
    });
});

resources/views/layout/admin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin - Crativa</title>
    <link rel="stylesheet" href="{{ asset('assets/vendors/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendors/css/vendor.bundle.base.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="shortcut icon" href="{{ asset('assets/img/favicon.png') }}" />
  </head>
  <body>
    <div class="container-scroller">
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href="/admin"><img src="{{ asset('assets/img/logo.svg') }}" alt="logo" /></a>
          <a class="navbar-brand brand-logo-mini" href="/admin"><img src="{{ asset('assets/img/logo-mini.svg') }}" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="nav-profile-img">
                  <img src="{{ asset('assets/img/faces/mike.jpeg') }}" alt="image">
                  <span class="availability-status online"></span>
                </div>
                <div class="nav-profile-text">
                  <p class="mb-1 text-black">
                    @if (Auth::user())
                    {{ Auth::user()->name }}
                     @endif
                  </p>
                </div>
              </a>
              <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}">
                  <i class="mdi mdi-logout me-2 text-primary"></i>Sign out</a>
              </div>
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
              <a class="nav-link">
                <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
              </a>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link" href="/admin">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('feature.index') }}">
                <span class="menu-title">Feature</span>
                <i class="mdi mdi-file-tree menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('image.index') }}">
                <span class="menu-title">Image</span>
                <i class="mdi mdi-folder-multiple-image menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('price.index') }}">
                <span class="menu-title">Price</span>
                <i class="mdi mdi-cash-multiple menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('contact.index') }}">
                <span class="menu-title">Contact</span>
                <i class="mdi mdi-contacts menu-icon"></i>
              </a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{{ route('banner.index') }}">
                <span class="menu-title">Banner</span>
                <i class="mdi mdi-checkbox-multiple-blank-outline menu-icon"></i>
              </a>
            </li>  
            <li class="nav-item">
              <a class="nav-link" href="{{ route('button.index') }}">
                <span class="menu-title">Button</span>
                <i class="mdi mdi-comment-processing menu-icon"></i>
              </a>
            </li>  
            <li class="nav-item sidebar-actions">
              <span class="nav-link">
              </span>
            </li>
          </ul>
        </nav>
        <!-- partial -->
      @yield('content')
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
              <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © Crativa.com 2024</span>
              <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> from FajarFathur.com</span>
            </div>
          </footer>
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <script src="assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="assets/vendors/chart.js/Chart.min.js"></script>
    <script src="assets/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="assets/js/off-canvas.js"></script>
    <script src="assets/js/hoverable-collapse.js"></script>
    <script src="assets/js/misc.js"></script>
    <script src="assets/js/dashboard.js"></script>
    <script src="assets/js/todolist.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>

    @stack('script')
  </body>
</html>

resources/views/layout/auth.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login Admin - Crativa</title>
    <link rel="stylesheet" href="{{ asset('assets/vendors/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendors/css/vendor.bundle.base.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="shortcut icon" href="{{ asset('assets/img/favicon.png') }}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row flex-grow">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="{{ asset('assets/img/logo.svg') }}">
                </div>
                <h4>Login to Your Admin Account</h4>
                <h6 class="font-weight-light">Enter your email & password to login</h6>
                @yield('content')
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="assets/js/off-canvas.js"></script>
    <script src="assets/js/misc.js"></script>
    <script src="../../assets/js/misc.js"></script>
  </body>
</html>

resources/views/layout/user.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('assets/css/icofont.min.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">
        <link rel="shortcut icon" href="{{ asset('assets/img/favicon.png') }}" />
        <title>Crativa</title>
    </head>
    <body>
        @yield('content')
    </body>
</html>