routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\PriceController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\ButtonController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\AuthenticationController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [UserController::class, 'Dashboard'])->name('dashboard');

Route::get('login', [AuthenticationController::class, 'form'])->name('login')->middleware('guest');
Route::post('authenticate', [AuthenticationController::class, 'authenticate']);
Route::get('logout', [AuthenticationController::class, 'logout'])->middleware('auth')->name('logout');


Route::middleware('auth')->group(function () {
    Route::get('/admin', [AdminController::class, 'Index'])->name('admin');
    // admin-feature
    Route::group(['prefix' => 'admin', 'as' => 'feature.'], function(){
        Route::get('/feature', [FeatureController::class, 'index'])->name('index');
        Route::get('/feature/create', [FeatureController::class, 'create'])->name('create');
        Route::post('/feature/store', [FeatureController::class, 'store'])->name('store');
        Route::get('/feature/edit/{feature}', [FeatureController::class, 'edit'])->name('edit');
        Route::post('/feature/update/{feature}', [FeatureController::class, 'update'])->name('update');
        Route::get('/feature/delete/{feature}', [FeatureController::class, 'destroy'])->name('delete');
    });    
    // admin-image
    Route::group(['prefix' => 'admin', 'as' => 'image.'], function(){
        Route::get('/image', [ImageController::class, 'index'])->name('index');
        Route::get('/image/create', [ImageController::class, 'create'])->name('create');
        Route::post('/image/store', [ImageController::class, 'store'])->name('store');
        Route::get('/image/edit/{image}', [ImageController::class, 'edit'])->name('edit');
        Route::post('/image/update/{image}', [ImageController::class, 'update'])->name('update');
        Route::get('/image/delete/{image}', [ImageController::class, 'destroy'])->name('delete');
    }); 
    // admin-price
    Route::group(['prefix' => 'admin', 'as' => 'price.'], function(){
        Route::get('/price', [PriceController::class, 'index'])->name('index');
        Route::get('/price/create', [PriceController::class, 'create'])->name('create');
        Route::post('/price/store', [PriceController::class, 'store'])->name('store');
        Route::get('/price/edit/{price}', [PriceController::class, 'edit'])->name('edit');
        Route::post('/price/update/{price}', [PriceController::class, 'update'])->name('update');
        Route::get('/price/delete/{price}', [PriceController::class, 'destroy'])->name('delete');
    });
    // admin-contact
    Route::group(['prefix' => 'admin', 'as' => 'contact.'], function(){
        Route::get('/contact', [ContactController::class, 'index'])->name('index');
        Route::get('/contact/create', [ContactController::class, 'create'])->name('create');
        Route::post('/contact/store', [ContactController::class, 'store'])->name('store');
        Route::get('/contact/edit/{contact}', [ContactController::class, 'edit'])->name('edit');
        Route::post('/contact/update/{contact}', [ContactController::class, 'update'])->name('update');
        Route::get('/contact/delete/{contact}', [ContactController::class, 'destroy'])->name('delete');
    });
    // admin-banner
    Route::group(['prefix' => 'admin', 'as' => 'banner.'], function(){
        Route::get('/banner', [BannerController::class, 'index'])->name('index');
        Route::get('/banner/create', [BannerController::class, 'create'])->name('create');
        Route::post('/banner/store', [BannerController::class, 'store'])->name('store');
        Route::get('/banner/edit/{banner}', [BannerController::class, 'edit'])->name('edit');
        Route::post('/banner/update/{banner}', [BannerController::class, 'update'])->name('update');
        Route::get('/banner/delete/{banner}', [BannerController::class, 'destroy'])->name('delete');
    });
    // admin-button
    Route::group(['prefix' => 'admin', 'as' => 'button.'], function(){
        Route::get('/button', [ButtonController::class, 'index'])->name('index');
        Route::get('/button/create', [ButtonController::class, 'create'])->name('create');
        Route::post('/button/store', [ButtonController::class, 'store'])->name('store');
        Route::get('/button/edit/{button}', [ButtonController::class, 'edit'])->name('edit');
        Route::post('/button/update/{button}', [ButtonController::class, 'update'])->name('update');
        Route::get('/button/delete/{button}', [ButtonController::class, 'destroy'])->name('delete');
    });
});

app/Models/Price.php
<?php

namespace App\Models;

use App\Models\Privileges;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Price extends Model
{
    use HasFactory;
    protected $table = 'price';
    protected $guarded = [];
    protected $hidden = ['created_at', 'updated_at'];

    public function privileges()
    {
        return $this->hasMany(Privileges::class);
    }
}

app/Http/Controllers/PriceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Price;
use App\Models\Privileges;
use Illuminate\Http\Request;

class PriceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $price = Price::all();
        $privilege = Privileges::all();

        return view('admin.price.index', compact('price', 'privilege'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $price = null;
        $privilege = null;

        return view('admin.price.action', compact('price', 'privilege'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $price = Price::create([
            'nama' => $request->nama,
            'harga' => $request->harga,
        ]);

        $privilege = $request->privilage;

        if (!is_null($privilege) && is_array($privilege)) {
         foreach ($privilege as $item) {
                Privileges::create([
                    'price_id' => $price->id,
                    'privilege' => $item
                ]);
            }
        }

        return redirect(route('price.index'));
    }


    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $price = Price::findorfail($id);

        return view('admin.price.action', compact('price'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $price = Price::findOrNew($id);
        $price->fill([
            'nama' => $request->nama,
            'harga' => $request->harga,
        ])->save();

        $price->privileges()->delete();
        $privilege = $request->privilage;

        if (!is_null($privilege) && is_array($privilege)) {
            foreach ($privilege as $item) {
                $price->privileges()->create([
                'privilege' => $item
                ]);
            }
        }
        return redirect()->route('price.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $price = Price::findOrFail($id);
        Privileges::where('price_id', $price->id) -> delete();
        $price->delete();
        return redirect()->route('price.index');
    }
}

resources/views/admin/Price/action.blade.php
@extends('layout.admin')

@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-cash-multiple"></i>
            </span> Price
        </h3>
        <nav aria-label="breadcrumb">
          <ul class="breadcrumb">
          </ul>
        </nav>
      </div>
      <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <form class="form-inline" action="{{ $price ? route('price.update', $price->id) : route('price.store')}}" method="post">
                    @csrf
                    @if ($price)
                        <input type="text" name="id" value="{{ $price -> id }}" hidden>
                    @endif
                    <div class="form-group">
                        <label for="">Nama</label>
                        <input type="text" name="nama" id="" class="form-control" placeholder="" value="{{ $price ? $price->nama : old('nama') }}" required aria-describedby="helpId">
                    </div>
                    <br>
                
                    <div class="form-group">
                        <label for="">Harga</label>
                        <input type="number" name="harga" id="" class="form-control" placeholder="" value="{{ $price ? $price->harga : old('harga') }}" required aria-describedby="helpId">
                    </div>
                    <div class="col-md-12 mb-3 mt-3" id="parentSubdesc">
                        @if ($price)
                            @foreach ($price->privileges as $item)
                                <div class="d-flex justify-content-end my-2 Subdesc">
                                    <div class="form-floating col-md-10">
                                        <input type="text" class="form-control" name="privilage[]" value="{{ $item ? $item->privilege : old('privilege') }}" placeholder="Privilage">
                                        <label>Privilege</label>
                                    </div>
                                    <button type="button" class="btn btn-gradient-success mx-2 my-2 btn-sm" id="plus"><i class="mdi mdi-plus-circle-outline"></i></button>
                                    <button type="button" class="btn btn-gradient-danger mx-2 my-2 btn-sm" id="minus"><i class="mdi mdi-minus-circle-outline"></i></button>
                                </div>
                            @endforeach
                        @else
                            <div class="d-flex justify-content-end my-2 Subdesc">
                                <div class="form-floating col-md-10">
                                    <input type="text" class="form-control" name="privilage[]" value="{{ $price ? $price->title : ''}}" placeholder="Privilage">
                                    <label>Privilege</label>
                                </div>
                                <button type="button" class="btn btn-gradient-success mx-2 my-2 btn-sm" id="plus"><i class="mdi mdi-plus-circle-outline"></i></button>
                                <button type="button" class="btn btn-gradient-danger mx-2 my-2 btn-sm" id="minus"><i class="mdi mdi-minus-circle-outline"></i></button>
                            </div>
                        @endif
                    </div>                    
                    <br>
                    <button type="submit" class="btn btn-gradient-primary btn-sm">Submit</button>
                    <button type="reset" class="btn btn-gradient-dark btn-sm">Reset</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    jQuery(document).ready(function($) {
        // Tambahkan kolom
        $("#plus").click(function() {
            var newColumn = $(".Subdesc:first").clone();
            newColumn.find("input").val(""); // Reset nilai input
            $("#parentSubdesc").append(newColumn);
        });

        // Hapus kolom
        $("#parentSubdesc").on("click", ".minus", function() {
            if ($("#parentSubdesc .Subdesc").length > 1) {
                $(this).closest(".Subdesc").remove();
            }
        });
    });
</script>
@endsection

resources/views/admin/Price/index.blade.php
@extends('layout.admin')
@section('content')
<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">
          <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-cash-multiple"></i>
          </span> Price
        </h3>
        <nav aria-label="breadcrumb">
          <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
              <a type="button" class="btn btn-gradient-info btn-icon-text btn-sm" href="{{ route('price.create') }}">
                <i class="mdi mdi-folder-plus btn-icon-prepend"></i>Tambah</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th> No </th>
                      <th> Nama </th>
                      <th> Harga </th>
                      <th> Privilege </th>
                      <th> Action </th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($price as $index=>$item)
                    <tr>
                        <td>{{ $index+1 }}</td>
                        <td>{{ $item->nama }}</td>
                        <td>{{ $item->harga }}</td>
                        <td>
                          @foreach($privilege->where('price_id', $item->id) as $items)
                          {{ $items->privilege }}<br>
                          @endforeach
                        </td>
                        <td>
                            <a type="button" class="btn btn-gradient-primary btn-icon-text btn-sm" href="{{ route('price.edit', $item->id) }}">
                            <i class="mdi mdi-lead-pencil btn-icon-prepend"></i>Edit</a>
                            <a type="button" class="btn btn-gradient-danger btn-icon-text btn-sm" href="javascript:void(0);" onclick="deleteData({{ $item->id }})">
                              <i class="mdi mdi-delete-forever btn-icon-prepend"></i>Hapus
                            </a>
                        </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      function deleteData(id) {
          var confirmation = window.confirm("Apakah Anda yakin?\nData akan dihapus secara permanen!");
  
          if (confirmation) {
              // Redirect ke route delete dengan menyertakan parameter id
              window.location.href = "{{ url('admin/price/delete') }}/" + id;
              // Jika menggunakan AJAX, Anda dapat menambahkan logika untuk menangani respons atau menampilkan alert sukses setelah penghapusan
          }
      }
  </script>
@endsection